# Generated by Django 5.0.3 on 2024-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champs1', models.CharField(max_length=45)),
                ('champs2', models.CharField(max_length=45)),
                ('champs3', models.BooleanField(default=True)),
                ('champs4', models.DateField()),
            ],
        ),
    ]
